name: Java CI with Maven

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Test with Maven
        run: mvn --batch-mode --file demoapp/pom.xml clean test